// <auto-generated />
using System;
using JustBlog.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustBlog.Core.Migrations
{
    [DbContext(typeof(JustBlogContext))]
    partial class JustBlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JustBlog.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Commodo massa sociosqu placerat eleifend iaculis vitae lectus lorem scelerisque praesent finibus",
                            Name = "Phasellus himenaeos",
                            UrlSlug = "vel-porttitor"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mattis ultricies elit a hendrerit fermentum nunc quis lobortis dignissim tristique id",
                            Name = "Odio tempor",
                            UrlSlug = "rhoncus-purus"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Et non quisque torquent cras luctus integer mi feugiat cursus volutpat eros",
                            Name = "Inceptos est",
                            UrlSlug = "nunc-tellus"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tristique mauris urna pellentesque nibh semper curabitur etiam et velit vehicula ac",
                            Name = "Sodales risus",
                            UrlSlug = "sit-integer"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tellus class nisi ac placerat placerat dolor eu ante maximus tempor at",
                            Name = "Vel augue",
                            UrlSlug = "rutrum-donec"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Porta ex platea consequat et per quam lacinia semper mattis metus lacinia",
                            Name = "Augue fames",
                            UrlSlug = "nunc-inceptos"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Pellentesque id condimentum pulvinar mattis lacinia in quis hendrerit vestibulum leo praesent",
                            Name = "Finibus eget",
                            UrlSlug = "himenaeos-euismod"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Arcu semper laoreet nostra dignissim sagittis quam porta sapien massa metus tellus",
                            Name = "Quam diam",
                            UrlSlug = "ad-ac"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Convallis felis lectus erat elit pulvinar ultrices vestibulum nibh nisl efficitur litora",
                            Name = "Ultricies massa",
                            UrlSlug = "blandit-aenean"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Leo et vitae mollis facilisis habitasse conubia donec eleifend eros arcu volutpat",
                            Name = "Urna taciti",
                            UrlSlug = "odio-egestas"
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CommentHeader")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(1026)
                        .HasColumnType("nvarchar(1026)");

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PostId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentHeader = "Sagittis diam quisque",
                            CommentText = "Et, quam vivamus maecenas nibh sagittis aenean laoreet, quam, habitasse. Faucibus vitae, lacinia amet, massa vehicula sit magna laoreet taciti non fames a.",
                            CommentTime = new DateTime(2022, 11, 1, 7, 28, 42, 676, DateTimeKind.Local).AddTicks(3392),
                            Email = "quis@enim.com",
                            Name = "Magna nullam",
                            PostId = 9
                        },
                        new
                        {
                            Id = 2,
                            CommentHeader = "Vehicula est auctor",
                            CommentText = "Habitasse donec hendrerit inceptos nam a eleifend, dignissim vel volutpat lacinia, euismod finibus arcu justo eros vestibulum.",
                            CommentTime = new DateTime(2022, 10, 31, 10, 3, 42, 676, DateTimeKind.Local).AddTicks(4572),
                            Email = "eros@faucibus.com",
                            Name = "Tristique urna",
                            PostId = 5
                        },
                        new
                        {
                            Id = 3,
                            CommentHeader = "Orci nunc ultricies",
                            CommentText = "Erat, sem, felis habitasse est tempor nisi, quis sed sit sodales ante, platea venenatis leo.",
                            CommentTime = new DateTime(2022, 10, 31, 11, 0, 42, 676, DateTimeKind.Local).AddTicks(5864),
                            Email = "pulvinar@lacinia.com",
                            Name = "Lobortis ullamcorper",
                            PostId = 2
                        },
                        new
                        {
                            Id = 4,
                            CommentHeader = "Sodales pretium sem",
                            CommentText = "Vehicula habitasse eu, vivamus a placerat semper class suspendisse diam.",
                            CommentTime = new DateTime(2022, 11, 5, 20, 38, 42, 676, DateTimeKind.Local).AddTicks(7066),
                            Email = "sed@odio.com",
                            Name = "Aliquam hendrerit",
                            PostId = 9
                        },
                        new
                        {
                            Id = 5,
                            CommentHeader = "Aliquam erat vel",
                            CommentText = "Dui, primis varius, a, lectus non, libero iaculis a facilisis purus malesuada tempor, interdum elementum platea. Ultrices, bibendum luctus, dui imperdiet orci auctor augue maecenas erat.",
                            CommentTime = new DateTime(2022, 11, 5, 1, 14, 42, 676, DateTimeKind.Local).AddTicks(8541),
                            Email = "diam@lectus.com",
                            Name = "Orci etiam",
                            PostId = 6
                        },
                        new
                        {
                            Id = 6,
                            CommentHeader = "Adipiscing dignissim arcu",
                            CommentText = "Dui feugiat felis proin volutpat hendrerit auctor mi, porta purus maecenas.",
                            CommentTime = new DateTime(2022, 11, 6, 17, 5, 42, 676, DateTimeKind.Local).AddTicks(9745),
                            Email = "adipiscing@semper.com",
                            Name = "Orci lectus",
                            PostId = 9
                        },
                        new
                        {
                            Id = 7,
                            CommentHeader = "Fringilla porttitor convallis",
                            CommentText = "Dapibus eu nam ultricies quis, finibus, mauris, urna, aenean proin convallis lorem volutpat vivamus vulputate sagittis, non eu, dictum.",
                            CommentTime = new DateTime(2022, 11, 1, 18, 16, 42, 677, DateTimeKind.Local).AddTicks(949),
                            Email = "quam@faucibus.com",
                            Name = "Pharetra auctor",
                            PostId = 3
                        },
                        new
                        {
                            Id = 8,
                            CommentHeader = "Magna condimentum lorem",
                            CommentText = "Vivamus nam magna est sagittis, tempor, diam pulvinar nec amet orci.",
                            CommentTime = new DateTime(2022, 11, 8, 8, 6, 42, 677, DateTimeKind.Local).AddTicks(2122),
                            Email = "sollicitudin@morbi.com",
                            Name = "Sagittis vestibulum",
                            PostId = 7
                        },
                        new
                        {
                            Id = 9,
                            CommentHeader = "Tempor consectetur pellentesque",
                            CommentText = "Morbi dignissim odio ut quisque fermentum ullamcorper ipsum facilisis nulla.",
                            CommentTime = new DateTime(2022, 10, 30, 0, 43, 42, 677, DateTimeKind.Local).AddTicks(3346),
                            Email = "ligula@commodo.com",
                            Name = "Auctor magna",
                            PostId = 3
                        },
                        new
                        {
                            Id = 10,
                            CommentHeader = "Malesuada sit metus",
                            CommentText = "Primis tortor ultrices, adipiscing suspendisse nibh, blandit tellus a et, lobortis ut feugiat, dui porta, laoreet.",
                            CommentTime = new DateTime(2022, 11, 7, 21, 53, 42, 677, DateTimeKind.Local).AddTicks(4518),
                            Email = "libero@nisi.com",
                            Name = "Facilisis urna",
                            PostId = 9
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("Post Content");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("Posted On");

                    b.Property<bool>("Published")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RateCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Rate Count");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Short Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("TotalRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Total Rate");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("View Count");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            PostContent = "Sagittis, nunc, ex, nulla tortor maecenas massa, erat, massa purus nostra, tellus, nunc in class quis. Dictum varius lorem, magna, nunc finibus a, quis, tincidunt dapibus vitae pulvinar. Phasellus placerat eu, auctor, per ad egestas litora sollicitudin magna, justo nulla sem dictumst. Laoreet, gravida nisi, aliquet sit eros leo, vel, ante, euismod, id elit. Magna, lorem, dui, quam, rhoncus sed, dolor varius enim, magna eros, sed tortor. Blandit, sociosqu suscipit conubia eget etiam inceptos adipiscing sagittis, ante nullam orci velit nisi, eros eu, magna nibh, primis.",
                            PostedOn = new DateTime(2022, 11, 6, 19, 10, 42, 673, DateTimeKind.Local).AddTicks(5224),
                            Published = true,
                            RateCount = 10,
                            ShortDescription = "Molestie tempor eros convallis nibh elit facilisis sed sagittis eu massa varius morbi",
                            Title = "Quam mauris amet",
                            TotalRate = 191,
                            UrlSlug = "pellentesque-posuere-ex",
                            ViewCount = 140
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            PostContent = "Vulputate sed varius, quam quis, nunc euismod, volutpat, molestie orci, dapibus lobortis luctus. Vestibulum, dictumst enim, cras porttitor, magna convallis consequat sollicitudin suscipit enim mattis, platea ultrices nec, lectus blandit fringilla. Tortor, leo non mollis lorem tristique viverra est varius, risus vel, nisi, odio, ante, id, ultricies finibus, enim. Tempor lobortis placerat ipsum eu sed rutrum nostra, non cras quam, massa, platea ligula. Leo amet augue in consectetur vehicula nulla convallis rutrum pellentesque ultrices ex.",
                            PostedOn = new DateTime(2022, 10, 30, 15, 13, 42, 673, DateTimeKind.Local).AddTicks(7402),
                            Published = true,
                            RateCount = 15,
                            ShortDescription = "Non metus massa ultrices cursus lectus aliquam eleifend malesuada arcu rutrum venenatis orci",
                            Title = "Mauris amet mi",
                            TotalRate = 248,
                            UrlSlug = "suscipit-sem-laoreet",
                            ViewCount = 180
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            PostContent = "Purus ligula mi placerat, auctor, sem turpis leo, maximus placerat vivamus blandit pellentesque massa arcu. Duis eget magna, primis hac tincidunt nulla malesuada maximus pulvinar neque, molestie gravida dictumst consequat euismod dignissim. Feugiat sodales arcu, dictum massa, aliquet enim, nisi, felis malesuada augue praesent odio tortor, aliquam pellentesque amet. Auctor fermentum dapibus eleifend, id, nisi blandit, nam porttitor ornare sem facilisis egestas luctus. Ac, finibus, conubia fusce nibh, lacus efficitur tempus interdum class tortor duis. Odio, commodo congue, imperdiet posuere suspendisse porttitor sed ornare amet. Eget vitae, suspendisse rhoncus eu, sem ultrices elit luctus, id enim euismod nullam mauris.",
                            PostedOn = new DateTime(2022, 11, 3, 18, 0, 42, 673, DateTimeKind.Local).AddTicks(9893),
                            Published = true,
                            RateCount = 19,
                            ShortDescription = "Eros cursus euismod donec venenatis euismod tempus auctor semper sem egestas porta consequat",
                            Title = "Tempus blandit lobortis",
                            TotalRate = 233,
                            UrlSlug = "sagittis-arcu-dui",
                            ViewCount = 183
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            PostContent = "Tellus dapibus interdum, mattis adipiscing mi, luctus, convallis blandit nec mi quam. Vitae accumsan lacinia arcu scelerisque amet, risus auctor, cursus erat volutpat tortor, lacus platea magna, nec eleifend class quam. Tellus himenaeos mollis consequat taciti tristique vivamus interdum fringilla, ut hendrerit nibh adipiscing ante. Varius tempus orci, pretium consectetur elit posuere suscipit massa, libero ligula, arcu interdum, sociosqu.",
                            PostedOn = new DateTime(2022, 11, 7, 8, 23, 42, 674, DateTimeKind.Local).AddTicks(1755),
                            Published = true,
                            RateCount = 22,
                            ShortDescription = "Sodales duis dui orci elementum erat sem tellus est mollis in mauris odio",
                            Title = "Torquent faucibus ornare",
                            TotalRate = 135,
                            UrlSlug = "blandit-arcu-conubia",
                            ViewCount = 225
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            PostContent = "Ac nisi, lacinia nibh, ullamcorper pharetra facilisis ante, lectus, varius. Non, nam tempor maecenas vehicula lectus, molestie vestibulum, suscipit imperdiet. Orci proin euismod, velit quis, neque cras conubia justo lobortis congue, mauris inceptos libero lectus facilisis. Sagittis, ligula vel, blandit eleifend, posuere, non, porttitor, est pharetra nibh id. Odio, mattis litora sagittis curabitur dolor commodo, mattis, lacinia, odio urna ante, rhoncus, neque. Curabitur dapibus cursus libero efficitur in quis lorem tincidunt nisl amet mauris. Sem, eros, molestie turpis dapibus tincidunt lacus arcu torquent phasellus elit justo gravida egestas.",
                            PostedOn = new DateTime(2022, 11, 3, 10, 36, 42, 674, DateTimeKind.Local).AddTicks(4294),
                            Published = true,
                            RateCount = 23,
                            ShortDescription = "Rhoncus dolor blandit orci congue dapibus sollicitudin sem quis mollis odio facilisis urna",
                            Title = "Sollicitudin mauris mi",
                            TotalRate = 140,
                            UrlSlug = "tellus-ligula-neque",
                            ViewCount = 149
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            PostContent = "Sed platea aptent dui molestie ligula, lacinia, mauris ultricies vestibulum, proin luctus venenatis in commodo vel. Mauris ornare lacinia non pulvinar mauris, ligula efficitur dolor purus odio. Ipsum volutpat, ornare class maximus euismod, magna, consequat erat, torquent libero dui commodo taciti integer mattis, auctor. Convallis taciti vitae bibendum, sem metus felis tempus tortor, nullam augue gravida imperdiet porttitor, fusce aenean.",
                            PostedOn = new DateTime(2022, 11, 3, 17, 36, 42, 674, DateTimeKind.Local).AddTicks(6025),
                            Published = true,
                            RateCount = 15,
                            ShortDescription = "Habitasse euismod porttitor nisi quisque diam varius dapibus phasellus nisi porttitor iaculis pharetra",
                            Title = "Interdum nibh commodo",
                            TotalRate = 249,
                            UrlSlug = "tellus-tempor-luctus",
                            ViewCount = 114
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            PostContent = "Ut ullamcorper dapibus class laoreet libero sem, curabitur rutrum neque, gravida. Aliquam placerat vel enim, a duis class pulvinar, neque, pulvinar nisi varius nec, tortor finibus, ornare. Rutrum mattis, porttitor viverra commodo, nam ultricies magna, ullamcorper luctus, hac risus quam vivamus auctor nibh arcu, pellentesque. Elit, ultricies vel pulvinar at litora curabitur consectetur sodales accumsan ullamcorper pulvinar. Diam erat finibus nibh massa donec quis, commodo leo nostra, litora quam, porta, euismod.",
                            PostedOn = new DateTime(2022, 10, 31, 3, 21, 42, 674, DateTimeKind.Local).AddTicks(8106),
                            Published = true,
                            RateCount = 19,
                            ShortDescription = "Porttitor euismod dolor id sit non sagittis sagittis vehicula quam massa ad semper",
                            Title = "Litora sodales eleifend",
                            TotalRate = 225,
                            UrlSlug = "felis-sagittis-class",
                            ViewCount = 138
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            PostContent = "Bibendum finibus, suspendisse pretium fringilla, cursus nisi diam adipiscing fusce varius eleifend, sit. Commodo et himenaeos dapibus mi, porta tellus, velit tristique adipiscing sollicitudin orci quis ante, posuere, sit. Erat, fringilla, est cursus sed lacinia, feugiat amet, quam ante, interdum. Aliquet ac sagittis, arcu quis, congue, volutpat, placerat et sem, augue nisl. Magna, ante sapien convallis amet elit velit ante, posuere praesent. Libero ultrices elit, velit vivamus commodo, bibendum erat at, elit dolor, suscipit urna, ex cras vitae sem, integer. Malesuada himenaeos tortor neque in ipsum id, lorem fusce viverra.",
                            PostedOn = new DateTime(2022, 11, 1, 17, 0, 42, 675, DateTimeKind.Local).AddTicks(648),
                            Published = true,
                            RateCount = 25,
                            ShortDescription = "Auctor elementum cras nisi blandit primis aliquet arcu ante purus justo rhoncus iaculis",
                            Title = "Tempor mattis quis",
                            TotalRate = 152,
                            UrlSlug = "iaculis-mauris-accumsan",
                            ViewCount = 280
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            PostContent = "Ultricies urna, pellentesque ornare eu ullamcorper mattis facilisis pharetra luctus arcu, conubia dictum metus a viverra gravida nulla. Eleifend, nam posuere eleifend placerat, nibh, eu vestibulum mauris, felis lorem cursus, nec eget accumsan. Litora leo hac pulvinar luctus, congue auctor, velit amet, quis, nisi, rutrum dui, dictum nulla, himenaeos. Urna convallis rhoncus donec ut consequat vitae porta, tortor feugiat, massa, commodo luctus blandit quisque himenaeos ante commodo. Enim sociosqu commodo, interdum, posuere pellentesque nisi, erat, nec, efficitur tempus est ex, rhoncus eleifend, malesuada accumsan adipiscing. Mauris quis, porttitor volutpat ligula ante, adipiscing egestas maecenas phasellus sagittis, leo, curabitur congue, non, justo. Finibus quis, maximus lacinia, laoreet erat, nostra, urna amet, turpis tempor justo.",
                            PostedOn = new DateTime(2022, 10, 31, 1, 0, 42, 675, DateTimeKind.Local).AddTicks(3237),
                            Published = true,
                            RateCount = 17,
                            ShortDescription = "Metus neque vivamus enim lorem proin viverra aenean pulvinar eu volutpat sagittis libero",
                            Title = "Orci et semper",
                            TotalRate = 160,
                            UrlSlug = "ex-dictumst-proin",
                            ViewCount = 138
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            PostContent = "Vulputate aliquet ac, pretium nisi molestie mi arcu cursus, sem proin inceptos. Amet, blandit, ante, sed nibh, laoreet, luctus tempus aenean nunc, nam. Eleifend, risus posuere, sem, id, commodo et, platea ligula eleifend. Pellentesque sed, tempor iaculis conubia ultrices, tellus adipiscing neque, mattis taciti non.",
                            PostedOn = new DateTime(2022, 11, 6, 11, 31, 42, 675, DateTimeKind.Local).AddTicks(5061),
                            Published = true,
                            RateCount = 12,
                            ShortDescription = "Cras faucibus sapien ex commodo pretium ornare lacinia ultrices ante curabitur rutrum quam",
                            Title = "Id turpis dapibus",
                            TotalRate = 273,
                            UrlSlug = "enim-dapibus-odio",
                            ViewCount = 242
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.PostTagMap", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTagMaps", (string)null);

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            TagId = 1
                        },
                        new
                        {
                            PostId = 2,
                            TagId = 2
                        },
                        new
                        {
                            PostId = 3,
                            TagId = 3
                        },
                        new
                        {
                            PostId = 4,
                            TagId = 4
                        },
                        new
                        {
                            PostId = 5,
                            TagId = 5
                        },
                        new
                        {
                            PostId = 6,
                            TagId = 6
                        },
                        new
                        {
                            PostId = 7,
                            TagId = 7
                        },
                        new
                        {
                            PostId = 8,
                            TagId = 8
                        },
                        new
                        {
                            PostId = 9,
                            TagId = 9
                        },
                        new
                        {
                            PostId = 10,
                            TagId = 10
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1026)
                        .HasColumnType("nvarchar(1026)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 29,
                            Description = "Nam tellus mattis vitae luctus aliquam fames mi feugiat in eleifend pretium facilisis",
                            Name = "Varius molestie sociosqu",
                            UrlSlug = "ut-fringilla-tortor"
                        },
                        new
                        {
                            Id = 2,
                            Count = 18,
                            Description = "Laoreet adipiscing nunc quam porta lectus sem phasellus elementum himenaeos primis mauris fermentum",
                            Name = "Cursus mattis arcu",
                            UrlSlug = "ultricies-hendrerit-turpis"
                        },
                        new
                        {
                            Id = 3,
                            Count = 19,
                            Description = "Fusce sodales consequat nulla placerat efficitur ante commodo orci velit himenaeos fringilla sem",
                            Name = "Aenean fermentum auctor",
                            UrlSlug = "tortor-nisi-venenatis"
                        },
                        new
                        {
                            Id = 4,
                            Count = 16,
                            Description = "Molestie placerat porta aenean quam facilisis iaculis in ad auctor nam fringilla neque",
                            Name = "Orci porttitor tristique",
                            UrlSlug = "congue-eros-curabitur"
                        },
                        new
                        {
                            Id = 5,
                            Count = 17,
                            Description = "A aenean proin mattis turpis lobortis fermentum curabitur etiam hendrerit orci erat leo",
                            Name = "Urna neque feugiat",
                            UrlSlug = "et-vehicula-neque"
                        },
                        new
                        {
                            Id = 6,
                            Count = 16,
                            Description = "Nibh a cursus congue eros dui ante lacinia commodo massa sodales nunc eu",
                            Name = "Class lorem turpis",
                            UrlSlug = "tellus-amet-platea"
                        },
                        new
                        {
                            Id = 7,
                            Count = 26,
                            Description = "Metus nulla lacinia himenaeos est sem sem habitasse eros eleifend magna auctor scelerisque",
                            Name = "Litora accumsan elit",
                            UrlSlug = "fusce-taciti-luctus"
                        },
                        new
                        {
                            Id = 8,
                            Count = 18,
                            Description = "Dictumst cursus varius duis quisque porttitor dapibus metus rutrum lobortis augue nullam enim",
                            Name = "Primis quis porttitor",
                            UrlSlug = "massa-phasellus-eleifend"
                        },
                        new
                        {
                            Id = 9,
                            Count = 21,
                            Description = "Vulputate augue conubia nullam id interdum congue molestie lobortis massa taciti lacinia dui",
                            Name = "Varius sagittis eu",
                            UrlSlug = "auctor-nibh-venenatis"
                        },
                        new
                        {
                            Id = 10,
                            Count = 25,
                            Description = "Vivamus augue mi sagittis maximus interdum pulvinar tortor pretium nisi donec cras nostra",
                            Name = "Felis fringilla faucibus",
                            UrlSlug = "venenatis-commodo-non"
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "06f42c04-8ca6-4a49-9123-612fe03d2eb1",
                            AboutMe = "Ultrices eros dolor magna porttitor commodo nullam tristique tellus sollicitudin",
                            AccessFailedCount = 0,
                            Age = 39,
                            ConcurrencyStamp = "7ede872d-e39a-4273-87d3-27d859332358",
                            Email = "kienct5@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KIENCT5@GMAIL.COM",
                            NormalizedUserName = "KIENCT5",
                            PasswordHash = "AQAAAAEAACcQAAAAEDMBVS3CxuVrtXKv14E1OdlSYO06y0AeLSPQ5aFALTnk/kqFP1t9u+Yo5pwpTazg8A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6f353210-216e-4eb7-9dd5-2974404311ba",
                            TwoFactorEnabled = false,
                            UserName = "kienct5"
                        },
                        new
                        {
                            Id = "0fd0513a-b066-4b9a-b7f7-3278406fbfa1",
                            AboutMe = "Eleifend volutpat nec lorem arcu enim tellus et ut cursus",
                            AccessFailedCount = 0,
                            Age = 20,
                            ConcurrencyStamp = "b612943e-ce40-418f-b97e-6af7809a20c6",
                            Email = "kienct6@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KIENCT6@GMAIL.COM",
                            NormalizedUserName = "KIENCT6",
                            PasswordHash = "AQAAAAEAACcQAAAAEL3b7oIqv9MLYM2aepCBFnV14+kDVl30Rz3XxY9LYR+dAVqau8obmxPUYOSI56l5rg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "242ef0d0-0e88-493e-a7d4-c8bb03ad2ee6",
                            TwoFactorEnabled = false,
                            UserName = "kienct6"
                        },
                        new
                        {
                            Id = "9c084822-4317-4634-aedd-df327edd8e02",
                            AboutMe = "In purus class laoreet volutpat felis erat ante elit consectetur",
                            AccessFailedCount = 0,
                            Age = 43,
                            ConcurrencyStamp = "851c7359-cf12-4d72-84ab-3c80ff6be64d",
                            Email = "kienct7@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KIENCT6@GMAIL.COM",
                            NormalizedUserName = "KIENCT7",
                            PasswordHash = "AQAAAAEAACcQAAAAEAeDGw0vdHY2VQd2O7yU/4lDRCHxVhpLxRA2Y054cE8bLO0hVjDVx0UP4OFCwZLg8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "50331815-6759-4110-ad5e-cefa412de249",
                            TwoFactorEnabled = false,
                            UserName = "kienct7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "24add274-998b-4784-911a-4e1fece82c63",
                            ConcurrencyStamp = "32b452fc-51d5-4a83-b411-e1906345a068",
                            Name = "Blog Owner",
                            NormalizedName = "BLOG OWNER"
                        },
                        new
                        {
                            Id = "7dd5ab7d-0181-4761-8d5b-60628b911ee5",
                            ConcurrencyStamp = "59019f1c-2e73-47ce-8990-788eaf2e672b",
                            Name = "Contributor",
                            NormalizedName = "CONTRIBUTOR"
                        },
                        new
                        {
                            Id = "96e4e54a-b52f-4ad0-a398-028954aa7c3a",
                            ConcurrencyStamp = "a1cc510d-6e48-472b-b0c4-908026afc5cd",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "56302830-a686-4fbe-a8ba-9b297ffbcc35",
                            ConcurrencyStamp = "e4bd5d34-1481-4d79-9a0a-e4412fe3e410",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "06f42c04-8ca6-4a49-9123-612fe03d2eb1",
                            RoleId = "24add274-998b-4784-911a-4e1fece82c63"
                        },
                        new
                        {
                            UserId = "0fd0513a-b066-4b9a-b7f7-3278406fbfa1",
                            RoleId = "7dd5ab7d-0181-4761-8d5b-60628b911ee5"
                        },
                        new
                        {
                            UserId = "9c084822-4317-4634-aedd-df327edd8e02",
                            RoleId = "96e4e54a-b52f-4ad0-a398-028954aa7c3a"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Comment", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Post", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JustBlog.Core.Entities.PostTagMap", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.Post", "Post")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustBlog.Core.Entities.Tag", "Tag")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustBlog.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostTagMaps");
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Tag", b =>
                {
                    b.Navigation("PostTagMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
